name: Ejecutar Pruebas UFT One

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  

    container:
      image: mcr.microsoft.com/windows/servercore:ltsc2022

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."

  test:
    runs-on: windows-latest  

    container:
      image: mcr.microsoft.com/windows/servercore:ltsc2022

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Running UFT One..."
          C:\path\to\uft\onetest.bat run "C:\path\to\uft\project.uft" --license-type free
          
