name: Ejecutar pruebas UFT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/uipath/uft-one-test@v1
        with:
          license-type: 'free'
          test-paths: 'prueba_google.vbs'
          generate-reports: true

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}
      
      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=/home/runner/work/UFT/UFT/" >> $GITHUB_OUTPUT
          
