name: Ejecutar Pruebas UFT One

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."

  test:
    runs-on: windows-latest  
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Running UFT One..."
          ./prueba_google.vbs
