name: Ejecutar Pruebas UFT One

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."

      - name: Test
        run: |
          echo "Running UFT One..."
          ./prueba_google.vbs
          
          # Establecer la ruta del artefacto de prueba
          echo "::set-output name=artifactPath::/home/runner/work/UFT/UFT/"

      - name: Upload Test Report
        if: always()  # Siempre carga el reporte de prueba independientemente del resultado
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: ${{ steps.Test.outputs.artifactPath }}
