name: Ejecutar pruebas UFT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/uipath/uft-one-test@v2.1.0
        with:
          license-type: 'free'
          test-paths: 'prueba_google.vbs'
          generate-reports: true

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.uipath-uft-one-test.outputs.report-path }}
          
