name: Ejecutar Pruebas UFT One

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  
      
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest  
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Build
        run: |
          echo "Building..."

      - name: Test
        run: |
          echo "Running UFT One..."
          ./prueba_google.vbs
          chmod 777  /home/runner/work/UFT/UFT/

      - name: Set output
        if: success() || failure()
        id: results
        run: echo "artifactPath=/home/runner/work/UFT/UFT/" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-report
          path: ${{ steps.results.outputs.artifactPath }}
